import type { DocumentItem, GraphNodeData } from '../types/admin'

export const adminDocuments: DocumentItem[] = [
  {
    id: 1,
    name: 'EU AI Act Overview.pdf',
    category: 'Regulation',
    chunks: 48,
    uploadedBy: 'Ava Chen',
    uploadedAt: '2026-07-28',
    status: 'Indexed',
  },
  {
    id: 2,
    name: 'DPDP Act Guidance.pdf',
    category: 'Policy',
    chunks: 36,
    uploadedBy: 'Noah Singh',
    uploadedAt: '2026-07-25',
    status: 'Indexed',
  },
  {
    id: 3,
    name: 'Hiring Risk Assessment.pdf',
    category: 'Risk',
    chunks: 22,
    uploadedBy: 'Liam Patel',
    uploadedAt: '2026-07-22',
    status: 'Processing',
  },
]

export const graphNodes: GraphNodeData[] = [
  {
    id: 'ai-recruitment',
    label: 'AI Recruitment',
    type: 'use-case',
    description: 'AI-assisted candidate screening and hiring workflows.',
    category: 'Use Case',
    connectedDocuments: ['EU AI Act Overview.pdf', 'Hiring Risk Assessment.pdf'],
    relevantPdf: 'EU AI Act Overview.pdf',
    indexedChunks: 14,
    relatedConcepts: ['Fairness', 'Human Oversight', 'Bias'],
    lastUpdated: '2h ago',
  },
  {
    id: 'eu-ai-act',
    label: 'EU AI Act',
    type: 'regulation',
    description: 'European framework for trustworthy AI systems with risk-based obligations.',
    category: 'Regulation',
    connectedDocuments: ['EU AI Act Overview.pdf'],
    relevantPdf: 'EU AI Act Overview.pdf',
    indexedChunks: 18,
    relatedConcepts: ['Transparency', 'Risk Management'],
    lastUpdated: '5h ago',
  },
  {
    id: 'dpdp-act',
    label: 'DPDP Act',
    type: 'regulation',
    description: 'India’s data protection law shaping consent and processing requirements.',
    category: 'Regulation',
    connectedDocuments: ['DPDP Act Guidance.pdf'],
    relevantPdf: 'DPDP Act Guidance.pdf',
    indexedChunks: 16,
    relatedConcepts: ['Consent', 'Privacy'],
    lastUpdated: '1d ago',
  },
  {
    id: 'fairness',
    label: 'Fairness',
    type: 'principle',
    description: 'Ensure outputs and decisions are equitable and free from unjust bias.',
    category: 'Governance Principle',
    connectedDocuments: ['Hiring Risk Assessment.pdf'],
    relevantPdf: 'Hiring Risk Assessment.pdf',
    indexedChunks: 9,
    relatedConcepts: ['Bias', 'Human Oversight'],
    lastUpdated: '3h ago',
  },
  {
    id: 'privacy',
    label: 'Privacy',
    type: 'rights',
    description: 'Protect individual privacy rights and personal data handling obligations.',
    category: 'Rights / Protection',
    connectedDocuments: ['DPDP Act Guidance.pdf'],
    relevantPdf: 'DPDP Act Guidance.pdf',
    indexedChunks: 12,
    relatedConcepts: ['Consent', 'Data Governance'],
    lastUpdated: '12h ago',
  },
  {
    id: 'bias',
    label: 'Bias',
    type: 'risk',
    description: 'Risk of skewed outcomes affecting candidate selection and evaluation.',
    category: 'Risk',
    connectedDocuments: ['Hiring Risk Assessment.pdf'],
    relevantPdf: 'Hiring Risk Assessment.pdf',
    indexedChunks: 7,
    relatedConcepts: ['Fairness', 'Accountability'],
    lastUpdated: '4h ago',
  },
  {
    id: 'human-oversight',
    label: 'Human Oversight',
    type: 'requirement',
    description: 'Keep meaningful human review and accountability in automated decisions.',
    category: 'Requirement',
    connectedDocuments: ['EU AI Act Overview.pdf'],
    relevantPdf: 'EU AI Act Overview.pdf',
    indexedChunks: 10,
    relatedConcepts: ['Transparency', 'Accountability'],
    lastUpdated: '6h ago',
  },
]

export const graphEdges = [
  { id: 'e1', source: 'ai-recruitment', target: 'eu-ai-act' },
  { id: 'e2', source: 'ai-recruitment', target: 'dpdp-act' },
  { id: 'e3', source: 'ai-recruitment', target: 'bias' },
  { id: 'e4', source: 'ai-recruitment', target: 'fairness' },
  { id: 'e5', source: 'eu-ai-act', target: 'human-oversight' },
  { id: 'e6', source: 'dpdp-act', target: 'privacy' },
  { id: 'e7', source: 'fairness', target: 'bias' },
  { id: 'e8', source: 'privacy', target: 'human-oversight' },
]
